// file not used for unit testing
import { testSetRoute, setVisitedDummy, getNbrsDummy, BFSDummy } from "../misc functions/LocationsFunctions"

const dummyMap = new Map()

dummyMap.set('02-AHU1', ['02-AHU1 dummy'])
dummyMap.set('02-AHU1 dummy', ['02-AHU1', 'SR 5 dummy'])
dummyMap.set('02-AHU2', ['02-AHU2 dummy'])
dummyMap.set('02-AHU2 dummy', ['02-AHU2', 'L2 Convenience Store dummy', 'SR 10 dummy'])
dummyMap.set('02-AHU4', ['Wire Centre dummy'])
dummyMap.set('Cerebro@SoC', ['Student Area'])
dummyMap.set('Computing Club', ['ICPC Lab dummy'])
dummyMap.set('DR 12', ['DR 12 dummy'])
dummyMap.set('DR 12 dummy', ['DR 12', 'TR 11', 'L2 Undergraduate Studies dummy', 'TR 10 dummy'])
dummyMap.set('Foyer Entrance', ['L2_Foyer', 'L2 Lift'])
dummyMap.set('ICPC Lab', ['ICPC Lab dummy'])
dummyMap.set('ICPC Lab dummy', ['ICPC Lab', 'L2 Convenience Store dummy', 'Wire Centre dummy', 'Computing Club'])
dummyMap.set('L2 Convenience Store', ['L2 Convenience Store dummy'])
dummyMap.set('L2 Convenience Store corner', ['L2 Convenience Store dummy', 'ICPC Lab dummy'])
dummyMap.set('L2 Convenience Store dummy', ['L2 Convenience Store', '02-AHU2 dummy', 'Stairs to COM2', 'L2 Convenience Store corner'])
dummyMap.set('L2 Lift', ['Foyer Entrance'])
dummyMap.set('L2 Undergraduate Studies', ['L2 Undergraduate Studies dummy'])
dummyMap.set('L2 Undergraduate Studies dummy', ['L2 Undergraduate Studies', 'Wire Centre dummy', 'DR 12 dummy', 'TR 11'])
dummyMap.set('L2_Foyer', ["Students' Lounge", 'SR 1', 'Student Area', 'SR 7 dummy', 'TR 10 dummy', 'Foyer Entrance'])
dummyMap.set('Linkway', ['SR 6 dummy', 'Makers@SoC dummy'])
dummyMap.set('Makers@SoC', ['Makers@SoC dummy'])
dummyMap.set('Makers@SoC dummy', ['Makers@SoC', 'SR 6 dummy', 'Linkway', 'SR 5 dummy'])
dummyMap.set('SR 1', ['L2_Foyer'])
dummyMap.set('SR 10', ['SR 10 dummy'])
dummyMap.set('SR 10 dummy', ['SR 10', 'VC Room', 'SR 9 dummy', '02-AHU2 dummy'])
dummyMap.set('SR 2', ['Student Area'])
dummyMap.set('SR 3', ['SR 8 dummy'])
dummyMap.set('SR 5', ['SR 5 dummy'])
dummyMap.set('SR 5 dummy', ['02-AHU1 dummy', 'SR 5', 'Makers@SoC dummy'])
dummyMap.set('SR 6', ['SR 6 dummy'])
dummyMap.set('SR 6 dummy', ['SR 6', 'Student Area', 'Linkway', 'Makers@SoC dummy'])
dummyMap.set('SR 7', ['SR 7 dummy'])
dummyMap.set('SR 7 dummy', ['L2_Foyer', 'SR 7', 'SR 8 dummy'])
dummyMap.set('SR 8', ['SR 8 dummy'])
dummyMap.set('SR 8 dummy', ['SR 7 dummy', 'SR 8', 'SR 3', 'SR 9 dummy'])
dummyMap.set('SR 9', ['SR 9 dummy'])
dummyMap.set('SR 9 dummy', ['SR 9', 'VC Room', 'SR 10 dummy', 'SR 8 dummy'])
dummyMap.set('Stair 5 (North)', ['Student Area'])
dummyMap.set('Stairs to COM 2', ['L2 Convenience Store dummy'])
dummyMap.set('Student Area', ['SR 6 dummy', 'Toilet near Stair 5 (North)', 'Stair 5 (North)', 'SR 2', 'L2_Foyer'])
dummyMap.set("Students' Lounge", ['L2_Foyer', 'TR 10 dummy'])
dummyMap.set('TR 10', ['TR 10 dummy'])
dummyMap.set('TR 10 dummy', ['TR 10', 'DR 12 dummy', "Students' Lounge", 'L2_Foyer'])
dummyMap.set('TR 11', ['DR 12 dummy', 'L2 Undergraduate Studies dummy'])
dummyMap.set('Toilet near Stair 5 (North)', ['Student Area'])
dummyMap.set('VC Room', ['SR 9 dummy', 'SR 10 dummy'])
dummyMap.set('Wire Centre', ['Wire Centre dummy'])
dummyMap.set('Wire Centre dummy', ['ICPC Lab dummy', '02-AHU4', 'L2 Undergraduate Studies dummy', 'Wire Centre'])

const dummyMap2 = new Map()

dummyMap2.set('02-AHU1', ['02-AHU1 dummy'])
dummyMap2.set('02-AHU1 dummy', ['02-AHU1', 'SR 5 dummy'])
dummyMap2.set('02-AHU2', ['02-AHU2 dummy'])
dummyMap2.set('02-AHU2 dummy', ['02-AHU2', 'L2 Convenience Store dummy', 'SR 10 dummy'])
dummyMap2.set('02-AHU4', ['Wire Centre dummy'])
dummyMap2.set('Cerebro@SoC', ['Student Area'])
dummyMap2.set('Computing Club', ['ICPC Lab dummy'])
dummyMap2.set('DR 12', ['DR 12 dummy'])
dummyMap2.set('DR 12 dummy', ['DR 12', 'TR 11', 'L2 Undergraduate Studies dummy', 'TR 10 dummy'])
dummyMap2.set('Foyer Entrance', ['L2_Foyer', 'L2 Lift'])
dummyMap2.set('ICPC Lab', ['ICPC Lab dummy'])
dummyMap2.set('ICPC Lab dummy', ['ICPC Lab', 'L2 Convenience Store dummy', 'Wire Centre dummy', 'Computing Club'])
dummyMap2.set('L2 Convenience Store', ['L2 Convenience Store dummy'])
dummyMap2.set('L2 Convenience Store corner', ['L2 Convenience Store dummy', 'ICPC Lab dummy'])
dummyMap2.set('L2 Convenience Store dummy', ['L2 Convenience Store', '02-AHU2 dummy', 'Stairs to COM2', 'L2 Convenience Store corner'])
dummyMap2.set('L2 Lift', ['Foyer Entrance'])
dummyMap2.set('L2 Undergraduate Studies', ['L2 Undergraduate Studies dummy'])
dummyMap2.set('L2 Undergraduate Studies dummy', ['L2 Undergraduate Studies', 'Wire Centre dummy', 'DR 12 dummy', 'TR 11'])
dummyMap2.set('L2_Foyer', ["Students' Lounge", 'SR 1', 'Student Area', 'SR 7 dummy', 'TR 10 dummy', 'Foyer Entrance'])
dummyMap2.set('Linkway', ['SR 6 dummy', 'Makers@SoC dummy'])
dummyMap2.set('Makers@SoC', ['Makers@SoC dummy'])
dummyMap2.set('Makers@SoC dummy', ['Makers@SoC', 'SR 6 dummy', 'Linkway', 'SR 5 dummy'])
dummyMap2.set('SR 1', ['L2_Foyer'])
dummyMap2.set('SR 10', ['SR 10 dummy'])
dummyMap2.set('SR 10 dummy', ['SR 10', 'VC Room', 'SR 9 dummy', '02-AHU2 dummy'])
dummyMap2.set('SR 2', ['Student Area'])
dummyMap2.set('SR 3', ['SR 8 dummy'])
dummyMap2.set('SR 5', ['SR 5 dummy'])
dummyMap2.set('SR 5 dummy', ['02-AHU1 dummy', 'SR 5', 'Makers@SoC dummy'])
dummyMap2.set('SR 6', ['SR 6 dummy'])
dummyMap2.set('SR 6 dummy', ['SR 6', 'Student Area', 'Linkway', 'Makers@SoC dummy'])
dummyMap2.set('SR 7', ['SR 7 dummy'])
dummyMap2.set('SR 7 dummy', ['L2_Foyer', 'SR 7', 'SR 8 dummy'])
dummyMap2.set('SR 8', ['SR 8 dummy'])
dummyMap2.set('SR 8 dummy', ['SR 7 dummy', 'SR 8', 'SR 3', 'SR 9 dummy'])
dummyMap2.set('SR 9', ['SR 9 dummy'])
dummyMap2.set('SR 9 dummy', ['SR 9', 'VC Room', 'SR 10 dummy', 'SR 8 dummy'])
dummyMap2.set('Stair 5 (North)', ['Student Area'])
dummyMap2.set('Stairs to COM 2', ['L2 Convenience Store dummy'])
dummyMap2.set('Student Area', ['SR 6 dummy', 'Toilet near Stair 5 (North)', 'Stair 5 (North)', 'SR 2', 'L2_Foyer'])
dummyMap2.set("Students' Lounge", ['L2_Foyer', 'TR 10 dummy'])
dummyMap2.set('TR 10', ['TR 10 dummy'])
dummyMap2.set('TR 10 dummy', ['TR 10', 'DR 12 dummy', "Students' Lounge", 'L2_Foyer'])
dummyMap2.set('TR 11', ['DR 12 dummy', 'L2 Undergraduate Studies dummy'])
dummyMap2.set('Toilet near Stair 5 (North)', ['Student Area'])
dummyMap2.set('VC Room', ['SR 9 dummy', 'SR 10 dummy'])
dummyMap2.set('Wire Centre', ['Wire Centre dummy'])
dummyMap2.set('Wire Centre dummy', ['ICPC Lab dummy', '02-AHU4', 'L2 Undergraduate Studies dummy', 'Wire Centre'])


setVisitedDummyCases = [
    [dummyMap, '02-AHU1 -> 02-AHU1 dummy -> SR 5 dummy -> Makers@SoC dummy -> SR 6 dummy -> Student Area -> L2_Foyer -> SR 7 dummy -> SR 8 dummy -> SR 9 dummy -> SR 10 dummy -> 02-AHU2 dummy -> 02-AHU2']
]

describe("Location functions", () => {
    test.each(setVisitedDummyCases)(
        'there is a route',
        (map, expected) => {
            console.log(expected);
            expect(testSetRoute(map)).toBe(expected);
        }
    )
})